apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-backend
  template:
    metadata:
      labels:
        app: lms-backend
    spec:
      containers:
        - name: lms-backend
          image: lms-image:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/lms
            - name: SPRING_DATASOURCE_USERNAME
              value: lmsuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: lmspassword
---
apiVersion: v1
kind: Service
metadata:
  name: lms-backend
spec:
  selector:
    app: lms-backend
  ports:
    - port: 8080
      targetPort: 8080
