apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-frontend
  template:
    metadata:
      labels:
        app: lms-frontend
    spec:
      containers:
        - name: lms-frontend
          image: react-lms-docker:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lms-frontend
spec:
  type: LoadBalancer
  selector:
    app: lms-frontend
  ports:
    - port: 80
      targetPort: 80
